---
- hosts: master
  gather_facts: False
  tasks:
    - name: add galaxy repo
      become: yes
      command: >
        helm repo add galaxy-helm-repo 
        https://pcm32.github.io/galaxy-helm-charts
      
    - name: install galaxy
      become: yes
      command: >
        helm install
        --version "{{ galaxy_chart_version }}"
        --set galaxy_image_tag="{{ galaxy_image_tag }}",use_ingress="yes",galaxy_backend_postgres=true,domain="{{ domain }}",external_ingress_controller="yes",galaxy_admin_email="{{ galaxy_admin_email }}",galaxy_admin_password="{{ galaxy_admin_password }}",galaxy_api_key="{{ galaxy_api_key }}",postgres.db_password="{{ galaxy_admin_password }}",galaxy_pvc="{{ galaxy_pvc }}",postgres.postgres_pvc="{{ postgres_pvc }}",galaxy_create_pvc="false"
        galaxy-helm-repo/galaxy
